/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface DexPoolInterface extends Interface {
    getFunction(nameOrSignature: "addLiquidity" | "reserveA" | "reserveB" | "swapAforB" | "tokenA" | "tokenB"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'addLiquidity', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'reserveA', values?: undefined): string;
encodeFunctionData(functionFragment: 'reserveB', values?: undefined): string;
encodeFunctionData(functionFragment: 'swapAforB', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'tokenA', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenB', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'addLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reserveA', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reserveB', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapAforB', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenA', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenB', data: BytesLike): Result;
  }

  

  export interface DexPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): DexPool;
    waitForDeployment(): Promise<this>;

    interface: DexPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addLiquidity: TypedContractMethod<
      [amountA: BigNumberish, amountB: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    reserveA: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    reserveB: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    swapAforB: TypedContractMethod<
      [amountInA: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    tokenA: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenB: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addLiquidity'): TypedContractMethod<
      [amountA: BigNumberish, amountB: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reserveA'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'reserveB'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'swapAforB'): TypedContractMethod<
      [amountInA: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tokenA'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenB'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }