/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'DefiIntegrator', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.DefiIntegrator__factory>
getContractFactory(name: 'DexPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.DexPool__factory>
getContractFactory(name: 'AssetToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AssetToken__factory>

  getContractAt(name: 'DefiIntegrator', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.DefiIntegrator>
getContractAt(name: 'DexPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.DexPool>
getContractAt(name: 'AssetToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AssetToken>

  deployContract(name: 'DefiIntegrator', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DefiIntegrator>
deployContract(name: 'DexPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DexPool>
deployContract(name: 'AssetToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AssetToken>

  deployContract(name: 'DefiIntegrator', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DefiIntegrator>
deployContract(name: 'DexPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DexPool>
deployContract(name: 'AssetToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AssetToken>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  